### PR TITLE
Upgrade OkHttp to 3.6.0. Based on 93a1d592d61b22

### PR DESCRIPTION
**Pull request by BenSchwab**
Upgrade to OkHttp 3.6.0. (Edit: not 3.8.0 but 3.6.0  facebook/react-native@3af9be5)

 This is blocking a handful of other library updates. 
Based on the commit here: https://github.com/facebook/react-native/commit/93a1d592d61b229d3dafe57d1590d286312cc0bf

After this lands I will create a new release and update Apps repo.

## Testing:
Built local version, and verified Android app builds and debugger still works. 

@lelandrichardson @gpeal

### CODE REVIEW

**Review by felipecsl — APPROVED** [review]
YAY finally

**Comment by gpeal** [comment]
Fyi https://github.com/facebook/react-native/commit/3af9be52b272b767b480ed4f989ddfd6146a56f8

**Comment by BenSchwab** [comment]
Oh, good find @gpeal, is there any more context to why it was downgraded? It's most important that we get onto 3.6.0 -- but if there is a serious reason why it RN needs to be on 3.6.0, we may run into random issues down the road if we accidently bump our version to 3.8.0 or have a dependency which does so.

**Comment by BenSchwab** [comment]
If I had to guess it would be this line from the okhttp changelog:

> Warning: this release is source-incompatible for Kotlin users. Nullability was previously ambiguous and lenient but now the compiler will enforce strict null checks.

FB probably didn't want to break build's for Kotlin. For sake of consistency, I will change this PR to use 3.6.0. But I think we should use 3.8.0 in our app.

**Comment by gpeal** [comment]
@BenSchwab I just pinged a few people to ask

**Comment by gpeal** [comment]
@felipecsl @BenSchwab https://github.com/facebook/react-native/issues/13996

**Comment by BenSchwab** [comment]
Got it. So we can upgrade safely to 3.6.0 in our app, and consider waiting for a 3.8.1 before going to 3.8.

**Comment by felipecsl** [comment]
sounds good to me!

**Pull request merged**
