### PR TITLE
Reapplying PR #14 to 0.45-canary branch

### PR DESCRIPTION
**Pull request by felipecsl**
Same changes as #14, but manually re-did it because of merge conflicts. Also simplified things a bit.
Im planning to send this upstream.

### CODE REVIEW

**Review by gpeal — APPROVED** [review]
Just stamping this. I can push an apps branch with this in it to test in the app.

**Comment by felipecsl** [comment]
I just did it @gpeal, however there is one incompatible change with `ReactMarker.setMarkerListener` which no longer exists

**Comment by lelandrichardson** [comment]
FYI the `ReactMarker` change is simple. It's just gone from `setMarkerListener` to `addListener`

**Comment by felipecsl** [comment]
@lelandrichardson awesome, I have the changes in the apps `felipe--rn-45-canary` branch

**Pull request merged**
